package pipeline

import (
	"fmt"
	"strings"
)

// SectionsSchema is the versioned name of the section-content contract. The
// model authors prose per topic; the program renders the structure around it.
const SectionsSchema = "docagent.sections/v1"

// SectionInput is what a caller supplies as artifact content.
//
// There is deliberately no field for a whole pre-rendered document. If the model
// could hand over finished markdown, its coverage record and its prose could
// disagree — a topic answered in the record and absent from the document. Here
// every section is keyed by topic id, so the two cannot drift.
type SectionInput struct {
	SchemaName string `json:"schemaName"`
	// Preamble is optional prose rendered after the title and before the first
	// section. It is additive context, never a substitute for a section.
	Preamble string `json:"preamble,omitempty"`
	// Sections maps a topic id to that section's markdown body, in the user's
	// documentation language.
	Sections map[string]string `json:"sections"`
}

// tbdMarker prefixes a section whose topic the user explicitly deferred. It
// keeps an acknowledged gap visible in the deliverable itself, not only in the
// status output, which is what global agent rule 8 asks for.
const tbdMarker = "**TBD** — not yet determined."

// Render builds the artifact from canonical English headings plus per-topic
// prose in the user's language.
//
// The headings come from the question bank and are written by this function,
// never by the model. That is what makes document structure verifiable without
// depending on the documentation language: the heading is machine vocabulary and
// the prose beneath it is not.
func Render(spec PhaseSpec, node Node, bank QuestionBank, input SectionInput, record AnswerRecord) ([]byte, error) {
	if spec.Kind == KindAudit {
		return nil, fmt.Errorf("phase %q is an audit and renders no artifact", spec.Phase)
	}

	status := make(map[string]AnswerStatus, len(record.Answers))
	for _, answer := range record.Answers {
		status[answer.TopicID] = answer.Status
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# %s — %s\n", node.ShortName, spec.DocumentTitle)
	fmt.Fprintf(&b,
		"\n<!-- Structure generated by doc-agent-ai from the question bank. "+
			"Headings are canonical; prose is authored. -->\n")

	if preamble := strings.TrimSpace(input.Preamble); preamble != "" {
		fmt.Fprintf(&b, "\n%s\n", preamble)
	}

	for _, topic := range bank.TopicsFor(spec.Phase, node.Type) {
		fmt.Fprintf(&b, "\n## %s\n\n", topic.Title)

		body := strings.TrimSpace(input.Sections[topic.ID])
		if status[topic.ID] == AnswerDeferred {
			fmt.Fprintf(&b, "%s\n", tbdMarker)
			if body != "" {
				fmt.Fprintf(&b, "\n%s\n", body)
			}
			continue
		}
		if body == "" {
			// Validation runs before this, so an empty answered section here means
			// a caller bypassed it. Fail rather than emit a hollow heading.
			return nil, fmt.Errorf("topic %q has no section content and is not deferred", topic.ID)
		}
		fmt.Fprintf(&b, "%s\n", body)
	}

	return []byte(b.String()), nil
}

// unknownSections returns section keys that are not topics of this phase. They
// signal drift between whoever produced the content and the bank, so they are
// reported rather than silently dropped.
func unknownSections(spec PhaseSpec, input SectionInput) []string {
	known := map[string]bool{}
	for _, topic := range spec.RequiredTopics {
		known[topic.ID] = true
	}

	var unknown []string
	for id := range input.Sections {
		if !known[id] {
			unknown = append(unknown, id)
		}
	}
	sortStrings(unknown)
	return unknown
}

// missingSections returns required topics that are answered but carry no prose.
// A deferred topic is exempt: its TBD marker is the content.
func missingSections(spec PhaseSpec, nodeType NodeType, bank QuestionBank,
	input SectionInput, record AnswerRecord) []string {

	status := make(map[string]AnswerStatus, len(record.Answers))
	for _, answer := range record.Answers {
		status[answer.TopicID] = answer.Status
	}

	var missing []string
	for _, topic := range bank.TopicsFor(spec.Phase, nodeType) {
		if status[topic.ID] == AnswerDeferred {
			continue
		}
		if strings.TrimSpace(input.Sections[topic.ID]) == "" {
			missing = append(missing, topic.ID)
		}
	}
	return missing
}

// sortStrings is a tiny insertion sort so section reports are deterministic
// without pulling in a dependency for a handful of ids.
func sortStrings(values []string) {
	for i := 1; i < len(values); i++ {
		for j := i; j > 0 && values[j] < values[j-1]; j-- {
			values[j], values[j-1] = values[j-1], values[j]
		}
	}
}

// RenderAuditReport draws the human-readable report for an audit phase.
//
// An audit writes no artifact of its own, and burying its findings in a state
// directory loses the part a person actually reads — real vaults hold refinement
// reports of several hundred lines. The structure here is computed from the
// recorded verdicts, so the report and the state the pipeline counts cannot
// disagree. The auditor's own analysis rides in `summary` and per-subject
// `notes`, clearly attributed to the auditor rather than presented as fact.
func RenderAuditReport(spec PhaseSpec, node Node, record AuditRecord) ([]byte, error) {
	if spec.Kind != KindAudit {
		return nil, fmt.Errorf("phase %q is not an audit phase", spec.Phase)
	}
	if spec.AuditRule == nil {
		return nil, fmt.Errorf("phase %q declares no audit rule", spec.Phase)
	}

	criteria := spec.AuditRule.PerSubjectVerdict

	var b strings.Builder
	fmt.Fprintf(&b, "# %s — %s Audit\n", node.ShortName, titleCase(spec.AuditRule.Subject))
	b.WriteString("\n<!-- Generated by doc-agent-ai from the recorded verdicts. " +
		"The tables are computed; the prose is the auditor's. -->\n")
	fmt.Fprintf(&b, "\nAudited: `%s`\n", spec.ArtifactName(node.ShortName))

	if summary := strings.TrimSpace(record.Summary); summary != "" {
		fmt.Fprintf(&b, "\n%s\n", summary)
	}

	failing := 0
	perCriterion := map[string]int{}
	for _, subject := range record.Subjects {
		clean := true
		for _, criterion := range criteria {
			if subject.Verdicts[criterion] == VerdictFail {
				perCriterion[criterion]++
				clean = false
			}
		}
		if !clean {
			failing++
		}
	}

	b.WriteString("\n## Summary\n\n| Measure | Value |\n|---|---|\n")
	fmt.Fprintf(&b, "| Subjects audited | %d |\n", len(record.Subjects))
	fmt.Fprintf(&b, "| Passing every criterion | %d |\n", len(record.Subjects)-failing)
	fmt.Fprintf(&b, "| With at least one failure | %d |\n", failing)
	for _, criterion := range criteria {
		if perCriterion[criterion] > 0 {
			fmt.Fprintf(&b, "| Failing `%s` | %d |\n", criterion, perCriterion[criterion])
		}
	}

	b.WriteString("\n## Verdicts\n\n| Subject |")
	for _, criterion := range criteria {
		fmt.Fprintf(&b, " %s |", titleCase(criterion))
	}
	b.WriteString("\n|---|")
	for range criteria {
		b.WriteString("---|")
	}
	b.WriteString("\n")
	for _, subject := range record.Subjects {
		fmt.Fprintf(&b, "| %s |", subject.ID)
		for _, criterion := range criteria {
			mark := "✅"
			if subject.Verdicts[criterion] == VerdictFail {
				mark = "❌"
			}
			fmt.Fprintf(&b, " %s |", mark)
		}
		b.WriteString("\n")
	}

	var withNotes []AuditSubject
	for _, subject := range record.Subjects {
		if strings.TrimSpace(subject.Notes) != "" {
			withNotes = append(withNotes, subject)
		}
	}
	if len(withNotes) > 0 {
		b.WriteString("\n## Findings\n")
		for _, subject := range withNotes {
			fmt.Fprintf(&b, "\n### %s\n\n%s\n", subject.ID, strings.TrimSpace(subject.Notes))
		}
	}

	return []byte(b.String()), nil
}

// titleCase capitalises a hyphenated identifier for display.
func titleCase(raw string) string {
	words := strings.Split(strings.ReplaceAll(raw, "-", " "), " ")
	for i, word := range words {
		if word == "" {
			continue
		}
		words[i] = strings.ToUpper(word[:1]) + word[1:]
	}
	return strings.Join(words, " ")
}
