package pipeline

import (
	"fmt"
	"strings"
)

// SectionsSchema is the versioned name of the section-content contract. The
// model authors prose per topic; the program renders the structure around it.
const SectionsSchema = "docagent.sections/v1"

// SectionInput is what a caller supplies as artifact content.
//
// There is deliberately no field for a whole pre-rendered document. If the model
// could hand over finished markdown, its coverage record and its prose could
// disagree — a topic answered in the record and absent from the document. Here
// every section is keyed by topic id, so the two cannot drift.
type SectionInput struct {
	SchemaName string `json:"schemaName"`
	// Preamble is optional prose rendered after the title and before the first
	// section. It is additive context, never a substitute for a section.
	Preamble string `json:"preamble,omitempty"`
	// Sections maps a topic id to that section's markdown body, in the user's
	// documentation language.
	Sections map[string]string `json:"sections"`
}

// tbdMarker prefixes a section whose topic the user explicitly deferred. It
// keeps an acknowledged gap visible in the deliverable itself, not only in the
// status output, which is what global agent rule 8 asks for.
const tbdMarker = "**TBD** — not yet determined."

// Render builds the artifact from canonical English headings plus per-topic
// prose in the user's language.
//
// The headings come from the question bank and are written by this function,
// never by the model. That is what makes document structure verifiable without
// depending on the documentation language: the heading is machine vocabulary and
// the prose beneath it is not.
func Render(spec PhaseSpec, node Node, bank QuestionBank, input SectionInput, record AnswerRecord) ([]byte, error) {
	if spec.Kind == KindAudit {
		return nil, fmt.Errorf("phase %q is an audit and renders no artifact", spec.Phase)
	}

	status := make(map[string]AnswerStatus, len(record.Answers))
	for _, answer := range record.Answers {
		status[answer.TopicID] = answer.Status
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# %s — %s\n", node.ShortName, spec.DocumentTitle)
	fmt.Fprintf(&b,
		"\n<!-- Structure generated by doc-agent-ai from the question bank. "+
			"Headings are canonical; prose is authored. -->\n")

	if preamble := strings.TrimSpace(input.Preamble); preamble != "" {
		fmt.Fprintf(&b, "\n%s\n", preamble)
	}

	for _, topic := range bank.TopicsFor(spec.Phase, node.Type) {
		fmt.Fprintf(&b, "\n## %s\n\n", topic.Title)

		body := strings.TrimSpace(input.Sections[topic.ID])
		if status[topic.ID] == AnswerDeferred {
			fmt.Fprintf(&b, "%s\n", tbdMarker)
			if body != "" {
				fmt.Fprintf(&b, "\n%s\n", body)
			}
			continue
		}
		if body == "" {
			// Validation runs before this, so an empty answered section here means
			// a caller bypassed it. Fail rather than emit a hollow heading.
			return nil, fmt.Errorf("topic %q has no section content and is not deferred", topic.ID)
		}
		fmt.Fprintf(&b, "%s\n", body)
	}

	return []byte(b.String()), nil
}

// unknownSections returns section keys that are not topics of this phase. They
// signal drift between whoever produced the content and the bank, so they are
// reported rather than silently dropped.
func unknownSections(spec PhaseSpec, input SectionInput) []string {
	known := map[string]bool{}
	for _, topic := range spec.RequiredTopics {
		known[topic.ID] = true
	}

	var unknown []string
	for id := range input.Sections {
		if !known[id] {
			unknown = append(unknown, id)
		}
	}
	sortStrings(unknown)
	return unknown
}

// missingSections returns required topics that are answered but carry no prose.
// A deferred topic is exempt: its TBD marker is the content.
func missingSections(spec PhaseSpec, nodeType NodeType, bank QuestionBank,
	input SectionInput, record AnswerRecord) []string {

	status := make(map[string]AnswerStatus, len(record.Answers))
	for _, answer := range record.Answers {
		status[answer.TopicID] = answer.Status
	}

	var missing []string
	for _, topic := range bank.TopicsFor(spec.Phase, nodeType) {
		if status[topic.ID] == AnswerDeferred {
			continue
		}
		if strings.TrimSpace(input.Sections[topic.ID]) == "" {
			missing = append(missing, topic.ID)
		}
	}
	return missing
}

// sortStrings is a tiny insertion sort so section reports are deterministic
// without pulling in a dependency for a handful of ids.
func sortStrings(values []string) {
	for i := 1; i < len(values); i++ {
		for j := i; j > 0 && values[j] < values[j-1]; j-- {
			values[j], values[j-1] = values[j-1], values[j]
		}
	}
}
