// Command genbanner reads the Zeen brand PNG and emits tui_banner_gen.go
// containing baked half-block cell-grid data for the TUI banner.
//
// Usage:
//
//	go run ./cmd/genbanner
//
// The generated file is committed; this tool is only re-run when the source
// PNG changes. It is a separate main package and never linked into the shipped
// binary.
//
// Output: tui_banner_gen.go in the repo root (package main).
package main

import (
	"fmt"
	"image"
	"image/color"
	_ "image/png"
	"os"
	"strings"
)

// brand palette sampled from Zeen_Dark.png
const (
	brandCyanHex = "#00A5E7" // rgb(0,165,231)   - blue Z mark
	brandDarkHex = "#0D1012" // rgb(13,16,18)    - dark square background
	brandGreyHex = "#E5E8EA" // rgb(229,232,234) - grey/light elements
)

// paletteIdx maps a pixel classification to a palette index.
// Palette order: 0=cyan, 1=dark, 2=grey.
const (
	idxCyan int8 = 0
	idxDark int8 = 1
	idxGrey int8 = 2
	idxNone int8 = -1 // transparent / unclassified → space
)

func main() {
	// Source PNG path relative to repo root.
	srcPath := "docs/assets/brand/Zeen_Dark.png"
	outPath := "tui_banner_gen.go"

	f, err := os.Open(srcPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "open %s: %v\n", srcPath, err)
		os.Exit(1)
	}
	defer f.Close()

	img, _, err := image.Decode(f)
	if err != nil {
		fmt.Fprintf(os.Stderr, "decode %s: %v\n", srcPath, err)
		os.Exit(1)
	}

	bounds := img.Bounds()
	W := bounds.Max.X
	H := bounds.Max.Y

	// Auto-crop: find the bounding box of dark OR blue pixels (ignore grey drop-shadow).
	minX, minY := W, H
	maxX, maxY := 0, 0
	for y := 0; y < H; y++ {
		for x := 0; x < W; x++ {
			cl := classifyPixel(img.At(x+bounds.Min.X, y+bounds.Min.Y))
			if cl == idxBlue || cl == idxDarkCls {
				if x < minX {
					minX = x
				}
				if y < minY {
					minY = y
				}
				if x > maxX {
					maxX = x
				}
				if y > maxY {
					maxY = y
				}
			}
		}
	}

	// Add a small margin and snap to even rows (half-block uses pairs).
	minX = max(0, minX-2)
	minY = max(0, minY-2)
	maxX = min(W-1, maxX+2)
	maxY = min(H-1, maxY+2)

	cropW := maxX - minX + 1
	cropH := maxY - minY + 1

	// Snap height to even.
	if cropH%2 != 0 {
		if maxY+1 < H {
			maxY++
		} else {
			minY--
		}
		cropH = maxY - minY + 1
	}

	// Welcome banner: ~24 columns wide.
	welcomeCols := 24
	cellW := cropW / welcomeCols
	if cellW < 1 {
		cellW = 1
	}
	rows := cropH / (cellW * 2)
	if rows < 1 {
		rows = 1
	}

	welcomeGrid := renderGrid(img, bounds.Min.X+minX, bounds.Min.Y+minY, cropW, cropH, welcomeCols, rows)

	// Compact banner: 1 row, ~8 columns — just the Z mark indicator.
	compactCols := 6
	compactRows := 1
	compactGrid := renderGrid(img, bounds.Min.X+minX, bounds.Min.Y+minY, cropW, cropH, compactCols, compactRows)

	// Emit Go source.
	var sb strings.Builder
	sb.WriteString("// Code generated by cmd/genbanner; DO NOT EDIT.\n")
	sb.WriteString("// Regenerate: go run ./cmd/genbanner\n")
	sb.WriteString("//\n")
	sb.WriteString("//go:generate go run ./cmd/genbanner\n")
	sb.WriteString("\n")
	sb.WriteString("package main\n\n")
	sb.WriteString("// bannerCell is one half-block glyph in the Zeen logo grid.\n")
	sb.WriteString("// Char is the rune (▀ or space). FgIdx/BgIdx index into bannerPalette;\n")
	sb.WriteString("// -1 means no color (transparent → plain space).\n")
	sb.WriteString("type bannerCell struct {\n")
	sb.WriteString("\tChar  rune\n")
	sb.WriteString("\tFgIdx int8\n")
	sb.WriteString("\tBgIdx int8\n")
	sb.WriteString("}\n\n")
	sb.WriteString("// bannerPalette maps FgIdx/BgIdx integers to hex color strings.\n")
	sb.WriteString(fmt.Sprintf("var bannerPalette = []string{%q, %q, %q}\n\n", brandCyanHex, brandDarkHex, brandGreyHex))
	sb.WriteString("// welcomeBanner is the full ~24-column Zeen Z mark + wordmark for the Welcome screen.\n")
	sb.WriteString("var welcomeBanner = ")
	sb.WriteString(formatGrid(welcomeGrid))
	sb.WriteString("\n\n")
	sb.WriteString("// compactBanner is the 1-row compact Z mark for inner screen headers.\n")
	sb.WriteString("var compactBanner = ")
	sb.WriteString(formatGrid(compactGrid))
	sb.WriteString("\n")

	if err := os.WriteFile(outPath, []byte(sb.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", outPath, err)
		os.Exit(1)
	}
	fmt.Printf("wrote %s (%d rows × %d cols welcome, %d rows × %d cols compact)\n",
		outPath, len(welcomeGrid), welcomeCols, len(compactGrid), compactCols)
}

// classification constants (internal to the generator).
const (
	idxBlue    = 10 // internal: isBlue pixel
	idxDarkCls = 11 // internal: isDark pixel
)

// classifyPixel returns an internal classification for a pixel.
func classifyPixel(c color.Color) int {
	r, g, b, a := c.RGBA()
	// Normalize from uint32 (0..65535) to uint8 (0..255).
	r8 := uint8(r >> 8)
	g8 := uint8(g >> 8)
	b8 := uint8(b >> 8)
	a8 := uint8(a >> 8)

	if a8 < 128 {
		return -1 // transparent
	}
	// Blue: a>128 && b>150 && r<120 && g>100
	if b8 > 150 && r8 < 120 && g8 > 100 {
		return idxBlue
	}
	// Dark: a>128 && r+g+b<150 && not blue
	if int(r8)+int(g8)+int(b8) < 150 {
		return idxDarkCls
	}
	return -1 // grey / other → skip in crop bbox calculation
}

// sample returns the palette cell index for a pixel at image coordinates (px, py).
func samplePaletteIdx(img image.Image, px, py int) int8 {
	c := img.At(px, py)
	r, g, b, a := c.RGBA()
	r8 := uint8(r >> 8)
	g8 := uint8(g >> 8)
	b8 := uint8(b >> 8)
	a8 := uint8(a >> 8)

	if a8 < 128 {
		return idxNone
	}
	if b8 > 150 && r8 < 120 && g8 > 100 {
		return idxCyan
	}
	if int(r8)+int(g8)+int(b8) < 150 {
		return idxDark
	}
	// Light grey pixels (wordmark area) → grey
	if int(r8)+int(g8)+int(b8) > 500 {
		return idxGrey
	}
	return idxNone
}

// renderGrid converts a region of the image into a half-block cell grid.
// imgOffX/Y are the top-left pixel coordinates in the image.
// cropW/cropH are the pixel dimensions of the region.
// cols/rows specify the output grid dimensions.
func renderGrid(img image.Image, imgOffX, imgOffY, cropW, cropH, cols, rows int) [][]bannerCell {
	cellW := cropW / cols
	cellH := cropH / rows
	if cellW < 1 {
		cellW = 1
	}
	if cellH < 2 {
		cellH = 2
	}

	grid := make([][]bannerCell, rows)
	for row := 0; row < rows; row++ {
		grid[row] = make([]bannerCell, cols)
		for col := 0; col < cols; col++ {
			// Sample center of top half-block and bottom half-block.
			topPx := imgOffX + col*cellW + cellW/2
			topPy := imgOffY + row*cellH + cellH/4
			botPx := topPx
			botPy := imgOffY + row*cellH + (3*cellH)/4

			fgIdx := samplePaletteIdx(img, topPx, topPy)
			bgIdx := samplePaletteIdx(img, botPx, botPy)

			var ch rune = ' '
			if fgIdx != idxNone || bgIdx != idxNone {
				ch = '▀'
			}
			// If only bg has color and fg is transparent, use ▄ or space with bg color.
			// Simplification: always use ▀ with fg=top, bg=bottom.
			if fgIdx == idxNone && bgIdx != idxNone {
				// Swap: render bottom color in foreground using ▄
				// For simplicity keep ▀ but swap — top=bottom color, bg=none.
				fgIdx = bgIdx
				bgIdx = idxNone
				ch = '▄'
			}

			grid[row][col] = bannerCell{Char: ch, FgIdx: fgIdx, BgIdx: bgIdx}
		}
	}
	return grid
}

// formatGrid serializes a [][]bannerCell as a Go composite literal.
func formatGrid(grid [][]bannerCell) string {
	var sb strings.Builder
	sb.WriteString("[][]bannerCell{\n")
	for _, row := range grid {
		sb.WriteString("\t{")
		for i, cell := range row {
			if i > 0 {
				sb.WriteString(", ")
			}
			var charStr string
			switch cell.Char {
			case '▀':
				charStr = "'▀'"
			case '▄':
				charStr = "'▄'"
			default:
				charStr = "' '"
			}
			sb.WriteString(fmt.Sprintf("{%s, %d, %d}", charStr, cell.FgIdx, cell.BgIdx))
		}
		sb.WriteString("},\n")
	}
	sb.WriteString("}")
	return sb.String()
}

func max(a, b int) int {
	if a > b {
		return a
	}
	return b
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}

// bannerCell is re-declared here for use in the generator logic.
// The actual type lives in tui_banner_gen.go (the generated file).
type bannerCell struct {
	Char  rune
	FgIdx int8
	BgIdx int8
}
